Changes so it can compile again
jam1garner/smush-discord pull request #7
Opened 2022-02-07 07:28 UTC by leeevye

Just made a few changes to make sure it still compiles properly and bumped version a bit to match up with other smash_info things

I'm very new to rust, but this all compiles for me so I assume I've done it right haha

2022-02-07 18:13 UTC, jam1garner requested changes

2022-02-07 18:13 UTC, jam1garner commented on Cargo.toml
> +smush_info_shared = { git = "https://github.com/leeevye/smush_info_shared.git" }
should probably be reverted

2022-02-08 00:16 UTC, leeevye commented on Cargo.toml
> +smush_info_shared = { git = "https://github.com/leeevye/smush_info_shared.git" }
Name has been reverted!

2022-02-08 00:16 UTC, jam1garner approved these changes

2022-02-08 00:16 UTC, merged